version: '3.8'

services:
  you2api:
    build: .
    container_name: you2api
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - YOU_API_KEY=${YOU_API_KEY}
      - YOU_API_BASE_URL=${YOU_API_BASE_URL:-https://api.you.com}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - API_RATE_LIMIT=${API_RATE_LIMIT:-100}
      - MAX_TOKENS=${MAX_TOKENS:-4096}
      - ENABLE_PROXY=${ENABLE_PROXY:-false}
      - PROXY_URL=${PROXY_URL:-}
      - PROXY_TIMEOUT_MS=${PROXY_TIMEOUT_MS:-5000}
    env_file:
      - .env
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/v1/models"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - you2api-network

  # 監控服務（可選，使用不同端口避免衝突）
  prometheus:
    image: prom/prometheus:latest
    container_name: you2api-prometheus
    ports:
      - "9091:9090"  # 改為9091避免衝突
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    depends_on:
      - you2api
    restart: unless-stopped
    networks:
      - you2api-network

  # Grafana 監控面板（可選，使用不同端口）
  grafana:
    image: grafana/grafana:latest
    container_name: you2api-grafana
    ports:
      - "3001:3000"  # 改為3001避免衝突
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus
    restart: unless-stopped
    networks:
      - you2api-network

volumes:
  prometheus_data:
  grafana_data:

networks:
  you2api-network:
    driver: bridge 